taglib: hot-fix for compile error in taglib
The code introduced by taglib-1.5-001-gio.patch does not compile
with gcc 4.5.3:

 tfile.cpp: In member function 'void TagLib::File::clear()':
 tfile.cpp:893:12: error: expected unqualified-id before '(' token

This is probably because the compiler optimizes away the empty
clearerr() method. Fix compilation by commenting out the call.