gcc: add patch to fix a compilation problem on x86
Without this patch, which I have pulled out of the gcc 4.7.2
patch directory of an older buildroot checkout, compilation
of gcc 4.7.3 breaks for me in the libitm folder:

 In file included from ../../../libitm/libitm_i.h:85:0,
                  from ../../../libitm/aatree.cc:28:
 ../../../libitm/config/x86/cacheline.h:55:3: error: '__m64' does not name a type

The problem has been reported upstream already, see
http://gcc.gnu.org/bugzilla/show_bug.cgi?id=52695

Signed-off-by: Sven Neumann <neumann@teufel.de>